// The selected theme determines which images to use when drawing the gems.
const themes = {
  farm: {
    name: "farm",
    1: "farm-1",
    2: "farm-2",
    3: "farm-3",
    4: "farm-4",
    5: "farm-5",
    6: "farm-6",
  },
  candy: {
    name: "candy",
    1: "candy-1",
    2: "candy-2",
    3: "candy-3",
    4: "candy-4",
    5: "candy-5",
    6: "candy-6",
  },
  web: {
    name: "web",
    1: "web-1",
    2: "web-2",
    3: "web-3",
    4: "web-4",
    5: "web-5",
    6: "web-6",
  },
  food: {
    name: "food",
    1: "food-1",
    2: "food-2",
    3: "food-3",
    4: "food-4",
    5: "food-5",
    6: "food-6",
  },
  ocean: {
    name: "ocean",
    1: "ocean-1",
    2: "ocean-2",
    3: "ocean-3",
    4: "ocean-4",
    5: "ocean-5",
    6: "ocean-6",
  },
};
