// The selected theme determines which images to use when drawing the gems.
const themes = {
  animals: {
    name: "animals",
    1: "animals-1-goose",
    2: "animals-2-cow",
    3: "animals-3-bear",
    4: "animals-4-cat",
    5: "animals-5-cheetah",
    6: "animals-6-snake",
  },
  candy: {
    name: "candy",
    1: "candy-1-red",
    2: "candy-2-orange",
    3: "candy-3-yellow",
    4: "candy-4-green",
    5: "candy-5-blue",
    6: "candy-6-purple",
  },
  food: {
    name: "food",
    1: "food-1-donut",
    2: "food-2-burger",
    3: "food-3-taco",
    4: "food-4-muffin",
    5: "food-5-hotdog",
    6: "food-6-croissant",
  },
  code: {
    name: "code",
    1: "code-1-node",
    2: "code-2-react",
    3: "code-3-webpack",
    4: "code-4-github",
    5: "code-5-javascript",
    6: "code-6-jquery",
  },
  ocean: {
    name: "ocean",
    1: "ocean-1-octopus",
    2: "ocean-2-turtle",
    3: "ocean-3-school",
    4: "ocean-4-fish",
    5: "ocean-5-crab",
    6: "ocean-6-pufferfish",
  },
};
